# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\untitled2.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UiTaskPageMain(object):
    def setupUi(self, Form):
        Form.setObjectName("Вариант")
        Form.resize(546, 456)
        Form.setWizardStyle(QtWidgets.QWizard.WizardStyle.ModernStyle)
        Form.setOption(QtWidgets.QWizard.WizardOption.NoCancelButton)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Вариант"))
