# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UiHistoryOfTasks(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(805, 363)
        self.table_history = QtWidgets.QTableWidget(Form)
        self.table_history.setGeometry(QtCore.QRect(10, 10, 781, 281))
        self.table_history.setObjectName("tableWidget")
        self.table_history.setColumnCount(0)
        self.table_history.setRowCount(0)
        self.btn_delete_all_history = QtWidgets.QPushButton(Form)
        self.btn_delete_all_history.setGeometry(QtCore.QRect(600, 300, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_delete_all_history.setFont(font)
        self.btn_delete_all_history.setObjectName("btn_delete_all_history")
        self.btn_import_to_csv = QtWidgets.QPushButton(Form)
        self.btn_import_to_csv.setGeometry(QtCore.QRect(180, 300, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_import_to_csv.setFont(font)
        self.btn_import_to_csv.setObjectName("btn_import_to_csv")
        self.btn_delete_choosen_history = QtWidgets.QPushButton(Form)
        self.btn_delete_choosen_history.setGeometry(QtCore.QRect(370, 300, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_delete_choosen_history.setFont(font)
        self.btn_delete_choosen_history.setObjectName("btn_delete_choosen_history")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_delete_all_history.setText(_translate("Form", "Очистить всю историю"))
        self.btn_import_to_csv.setText(_translate("Form", "Импортировать в CSV"))
        self.btn_delete_choosen_history.setText(_translate("Form", "Удалить выбранную строку"))
