# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\lastpage.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UiLastPage(object):
    def setupUi(self, Form):
        Form.setObjectName("Результат")
        Form.resize(445, 337)
        self.lbl_result = QtWidgets.QLabel(Form)
        self.lbl_result.setGeometry(QtCore.QRect(30, 20, 401, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lbl_result.setFont(font)
        self.lbl_result.setObjectName("label")
        self.lbl_mark = QtWidgets.QLabel(Form)
        self.lbl_mark.setGeometry(QtCore.QRect(30, 100, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lbl_mark.setFont(font)
        self.lbl_mark.setObjectName("label_2")
        self.btn_OK = QtWidgets.QPushButton(Form)
        self.btn_OK.setGeometry(QtCore.QRect(360, 300, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_OK.setFont(font)
        self.btn_OK.setObjectName("pushButton")
        self.lbl_image = QtWidgets.QLabel(Form)
        self.lbl_image.setGeometry(QtCore.QRect(40, 180, 141, 141))
        self.lbl_image.setText("")
        self.lbl_image.setObjectName("lbl_image")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Результат"))
        self.lbl_result.setText(_translate("Form", "Вы решили"))
        self.lbl_mark.setText(_translate("Form", "Оценка - "))
        self.btn_OK.setText(_translate("Form", "OK"))
